export const OWNER_PASSWORD = 'admin';

export const INITIAL_BOOKS = [
    {
        id: 1,
        title: 'Pride and Prejudice',
        author: 'Jane Austen',
        description: 'A witty examination of manners, marriage, and morality as Elizabeth Bennet navigates Regency-era society and her evolving feelings for Mr. Darcy.',
        price: 0.00,
        coverImage: 'https://images.unsplash.com/photo-1455884981818-54cb785db6fc?auto=format&fit=crop&w=900&q=80',
        genre: 'Classic Romance',
        publisher: 'Project Gutenberg (EBook #1342)',
        stock: 999,
    },
    {
        id: 2,
        title: 'The Adventures of Sherlock Holmes',
        author: 'Arthur Conan Doyle',
        description: 'Twelve of Sherlock Holmes’s most celebrated cases introduce the brilliant detective and Dr. Watson as they unravel crimes across Victorian London.',
        price: 0.00,
        coverImage: 'https://images.unsplash.com/photo-1489515217757-5fd1be406fef?auto=format&fit=crop&w=900&q=80',
        genre: 'Detective Fiction',
        publisher: 'Project Gutenberg (EBook #1661)',
        stock: 999,
    },
    {
        id: 3,
        title: 'Frankenstein; or, The Modern Prometheus',
        author: 'Mary Wollstonecraft Shelley',
        description: 'Victor Frankenstein’s quest to animate life yields a sentient creature and a gothic exploration of ambition, responsibility, and isolation.',
        price: 0.00,
        coverImage: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?auto=format&fit=crop&w=900&q=80',
        genre: 'Gothic Science Fiction',
        publisher: 'Project Gutenberg (EBook #84)',
        stock: 999,
    },
    {
        id: 4,
        title: 'The Count of Monte Cristo',
        author: 'Alexandre Dumas',
        description: 'Falsely imprisoned Edmond Dantès escapes, discovers treasure, and returns as the Count of Monte Cristo to balance the scales of justice.',
        price: 0.00,
        coverImage: 'https://images.unsplash.com/photo-1528207776546-365bb710ee93?auto=format&fit=crop&w=900&q=80',
        genre: 'Adventure',
        publisher: 'Project Gutenberg (EBook #1184)',
        stock: 999,
    },
    {
        id: 5,
        title: 'The Picture of Dorian Gray',
        author: 'Oscar Wilde',
        description: 'A Faustian tale in which Dorian Gray’s portrait bears the marks of his corruption while he pursues pleasure in Victorian London.',
        price: 0.00,
        coverImage: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=900&q=80',
        genre: 'Philosophical Fiction',
        publisher: 'Project Gutenberg (EBook #174)',
        stock: 999,
    },
    {
        id: 6,
        title: 'Moby-Dick; or, The Whale',
        author: 'Herman Melville',
        description: 'Captain Ahab’s obsessive pursuit of the white whale is chronicled by Ishmael in this epic meditation on obsession, fate, and the sea.',
        price: 0.00,
        coverImage: 'https://images.unsplash.com/photo-1523475472560-d2df97ec485c?auto=format&fit=crop&w=900&q=80',
        genre: 'Maritime Epic',
        publisher: 'Project Gutenberg (EBook #2701)',
        stock: 999,
    },
];


export const INITIAL_PAGE_CONTENT = {
    heroTitle: 'Timeless Classics, Ready to Read',
    heroSubtitle: 'Browse a librarian-curated shelf of public domain literature sourced from Project Gutenberg and other open archives.',
    heroImage: 'https://images.unsplash.com/photo-1516979187457-637abb4f9353?auto=format&fit=crop&w=1887&q=80',
    aboutContent: 'This catalog highlights public domain masterpieces that readers can legally download for free. Each title links back to its Project Gutenberg record so you can continue exploring trusted editions, background essays, and volunteer notes.',
    logoImage: '',
};
