# Netlify build configuration for BooksLb-3

[build]
  # Command Netlify will run to build your site
  command = "npm run build"

  # Folder that contains the built site ready for deployment
  publish = "dist"

# Redirect rule for Single Page Applications (SPA)
# Ensures routes like /books/123 work correctly
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# (Optional) Local development settings for Netlify Dev
# Uncomment if you use `netlify dev` command locally
#[dev]
#  command = "npm run dev"
#  port = 3000
#  publish = "dist"

# More info on configuring this file:
# https://docs.netlify.com/configure-builds/file-based-configuration/